### ISSUE TITLE
`esp_idf_sys::ledc_timer_config_t` does not have this field error + esp-idf 5.1 needs esp-idf-hal master branch

### ISSUE THREAD

**Issue by Vollbrecht** [esp-rs/esp-idf-template#128]
We already fixed it inside [esp-idf-hal](https://github.com/esp-rs/esp-idf-hal/commit/2ab4c709f170643daf5e419ac91d6845f8567a68) but the fix is not release. So if you are generating a template with esp-idf 5.1 please use the esp-idf-hal master branch till the fix is release. Sorry for the inconvenience and thanks for cooperation :smiley_cat: 

Edit: to build against the master branch you can simply add the following into your Cargo.toml
```toml
[patch.crates-io]
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal" }
```
