### ISSUE TITLE
Where to set the logging level at compile-time?

### ISSUE THREAD

**Issue by victorbnl** [esp-rs/esp-idf-template#222]
Where is the best place to set the logging level at compile time with this project template? Running `RUST_LOG="debug" cargo run` does not print debug logs, I’m guessing because the variable is not passed to the ESP’s runtime environment.

The best solution would appear to be setting the log crate’s feature flag as follows, however I’d like to set a different logging level for each profile, and per-profile rustflags are currently unstable.

```toml
[profile.release]
rustflags = ["-C", "release_max_level_info"]

[profile.debug]
rustflags = ["-c", "release_max_level_debug"]
```
